//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab5_fixed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int StudentBookNumber { get; set; }
        public int GroupCode { get; set; }
        public string Address { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
